'use strict';

export const LOADING = 'LOADING';
export const GLOBAL = 'FETCH_GLOBAL';
export const LIST_PROJECT = 'LIST_PROJECT';
export const SHOW_PROJECT = 'SHOW_PROJECT';
export const LIST_FEED_SOURCE = 'LIST_FEED_SOURCE';
export const LIST_FEED_SOURCE_TYPE = 'LIST_FEED_SOURCE_TYPE';
export const TOPIC_CREATE = 'TOPIC_CREATE';
export const TOPIC_DELETE = 'TOPIC_DELETE';
export const TOPIC_UPDATE = 'TOPIC_UPDATE';
export const TOPIC_FEED_UPDATE = 'TOPIC_FEED_UPDATE';
export const TOPIC_SUBSCRIBE = 'TOPIC_SUBSCRIBE';
export const TOPIC_SUBSCRIBE_MOVE = 'TOPIC_SUBSCRIBE_MOVE';
export const TOPIC_SUBSCRIBE_DELETE = 'TOPIC_SUBSCRIBE_DELETE';
export const COLLECT_PROJECT = 'COLLECT_PROJECT';
export const CANCEL_COLLECT_PROJECT = 'CANCEL_COLLECT_PROJECT';
export const LIST_PREVIEWFEED_PROJECTS = 'LIST_PREVIEWFEED_PROJECTS';
export const PREVIEW_PROJECT = 'PREVIEW_PROJECT';
export const SAVE_COLLECTION_TAGS = 'SAVE_COLLECTION_TAGS';

export const HOME_SLIDERS = 'HOME_SLIDERS';
export const HOT_SUBSCRIBES = 'HOT_SUBSCRIBES';
export const RECOMMEND_SUBSCRIBES = 'RECOMMEND_SUBSCRIBES';
export const HOT_PROJECTS = 'HOT_PROJECTS';
export const SELECTION_PROJECTS = 'SELECTION_PROJECTS';
export const RECOMMEND_PROJECTS = 'RECOMMEND_PROJECTS';

//Guide页面相关Action Types
export const GUIDE_STEP = "GUIDE_STEP";
export const GUIDE_STEP_RESET = "GUIDE_STEP_RESET";
export const GUIDE_INTEREST_LIST = "GUIDE_INTEREST_LIST";
export const GUIDE_ACCOUNT_LIST = "GUIDE_ACCOUNT_LIST";
export const GUIDE_SAVE = "GUIDE_SAVE";

//Preview
export const PREVIEW = 'PREVIEW';
